apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azurefilesecret
    shareName: jupyterhub-shared
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefiles-jupyterhub-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: jupyterhub-pv
  storageClassName: azurefile
  resources:
    requests:
      storage: 20Gi