hub:
  db:
    type: sqlite-memory

singleuser:
  defaultUrl: "/lab"
  networkPolicy:
    enabled: false
  storage:
    type: none
  image:
    name: kringen/jupyter-spark
    tag: 1.2.1
  lifecycleHooks:
    postStart:
      exec:
        command: 
          - "sh"
          - "-c"
          - >
            echo "spark.driver.host=$(hostname -i)" > /usr/local/spark/conf/spark-defaults.conf


