hub:
  db:
    type: sqlite-memory

singleuser:
  defaultUrl: "/lab"
  networkPolicy:
    enabled: false
  storage:
    type: none # Do not persist non-shared storage
    extraVolumes:
    - name: jupyterhub-sharedscratch-rw
      persistentVolumeClaim:
        claimName: azurefiles-jupyterhub-pvc
    - name: jupyterhub-data-rw
      persistentVolumeClaim:
        claimName: azurefiles-spark-pvc
    extraVolumeMounts:
    - name: jupyterhub-sharedscratch-rw
      mountPath: /home/jovyan/shared
      subPath: shared  
    - name: jupyterhub-data-rw
      mountPath: /srv/spark/data  
  image:
    name: kringen/jupyter-spark
    tag: 1.2.1
  lifecycleHooks:
    postStart:
      exec:
        command: 
          - "sh"
          - "-c"
          - >
            echo "spark.driver.host=$(hostname -i)" > /usr/local/spark/conf/spark-defaults.conf


