master:
  claimName: azurefiles-spark-pvc

worker:
  claimName: azurefiles-spark-pvc

persistentVolume:
  name: spark-pv
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteMany
    storageClassName: azurefile
    azureFile:
      secretName: azurefilesecret
      shareName: spark-shared
      readOnly: false
    mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl

persistentVolumeClaim:
  name: azurefiles-spark-pvc
  storage: 20Gi
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
