apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.master.name }}
  labels:
    app: {{ .Values.master.name }}
spec:
  ports:
{{- with .Values.master.service.ports }}
{{ toYaml . | indent 2 }}
{{- end }}
  clusterIP: None
  selector:
    app: {{ .Values.master.name }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.master.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.master.name }} # has to match .spec.template.metadata.labels
  serviceName: {{ .Values.master.name }}
  replicas: {{ .Values.master.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.master.name }} # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.master.container.name }}
        image: {{ printf "%s/%s:%s" .Values.master.container.imageRepository .Values.master.container.image .Values.master.container.imageVersion }}
        env:
{{- with .Values.master.container.env }}
{{ toYaml . | indent 8 }}
{{- end }}
        command: 
          {{  range .Values.master.container.command }}
            - {{ . }}
          {{ end }}
        args: 
          {{  range .Values.master.container.args }}
            - {{ . }}
          {{ end }}
        ports:
{{- with .Values.master.container.ports }}
{{ toYaml . | indent 8 }}
{{- end }}
        volumeMounts:
        - name: data-volume
          mountPath: {{ .Values.master.container.dataVolumeMountPath }}
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.master.claimName }}
